### PR TITLE
Adding inst/doc/  examples

### PR DESCRIPTION
**Pull request by nashjc**
Somehow old pull request hanging around. Editing it to new (R CMD check tested) version.

---------------------------------
Not totally convinced that these are useful, but I suspect that they can be helpful to users.
I'm also considering a vignette to illustrate usage. Opinion/suggestions welcome.

Best, JN

### CODE REVIEW

**Review by jlmelville — APPROVED** [review]
Looks good to me. I think these are useful indeed.

Is the `NEWS` file in any particular format? I would lean towards doing it in markdown, but I don't think it matters.

Thank you for doing this.

**Comment by jlmelville** [comment]
@nashjc I think this contribution is valuable enough on its own that I would be happy to merge this and then any vignette would be a separate PR. If that is agreeable to you, I will merge. Otherwise if you are in the middle of a big change you don't want to move to a new branch, I am happy to wait.

**Comment by nashjc** [comment]
Think it's ready to go.

**Comment by jlmelville** [comment]
Thanks @nashjc I'll start on this ASAP

**Comment by jlmelville** [comment]
@nashjc I am inclined to merge this and then tweak some things on my branch. Some questions about this:

* when I try to run `devtools::check` on this, it always deletes everything in `inst/doc`, which is a bit disastrous. Is there a reason to *not* just move this into `vignettes` and build it manually? I can (probably) make this work.
* if I do this, I can probably turn this into an "article" via pkgdown, which would automatically generate an HTML version of the page. I've never really looked at generating a PDF as well. How much do you want a permanent PDF document as part of this vs having it as a web page that would live on github pages?

**Comment by jlmelville** [comment]
I'm going to merge this, then work on a branch on my repo to do any needed clean-up. Thank you for this @nashjc!

**Pull request merged**
